/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Info */
        get: operations["info_v1_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_v1_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/anonymize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anonymize Endpoint */
        post: operations["anonymize_endpoint_v1_anonymize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deanonymize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deanonymize Endpoint */
        post: operations["deanonymize_endpoint_v1_deanonymize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Endpoint */
        post: operations["export_endpoint_v1_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Document */
        post: operations["process_document_v1_documents_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prompts */
        get: operations["list_prompts_v1_prompts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/prompts/{prompt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prompt */
        get: operations["get_prompt_v1_prompts__prompt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage */
        get: operations["usage_v1_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Text */
            text: string;
            /**
             * Language
             * @default pl
             */
            language: string;
            /**
             * Custom Rules
             * @description Optional local custom regex rules. At most 25 rules are accepted; each pattern/regex value is limited to 256 characters and must compile. Matches are returned as CUSTOM entities with source=regex.
             */
            custom_rules?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** Entities */
            entities: components["schemas"]["DetectedEntity"][];
        };
        /** AnonymizeRequest */
        AnonymizeRequest: {
            /** Text */
            text: string;
            /**
             * Language
             * @default pl
             */
            language: string;
            /** Entities */
            entities?: components["schemas"]["DetectedEntity"][] | null;
        };
        /** AnonymizeResponse */
        AnonymizeResponse: {
            /** Anonymized Text */
            anonymized_text: string;
            replacement_map: components["schemas"]["ReplacementMap"];
            /** Offset Map */
            offset_map?: components["schemas"]["OffsetMapEntry"][];
        };
        /** Block */
        Block: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "paragraph" | "heading" | "table_cell" | "page_break";
            /** Page */
            page?: number | null;
        };
        /** Body_process_document_v1_documents_process_post */
        Body_process_document_v1_documents_process_post: {
            /** File */
            file: string;
            /**
             * Force Ocr
             * @default false
             */
            force_ocr: boolean;
            /**
             * Language
             * @default pl
             */
            language: string;
        };
        /** DeanonymizeRequest */
        DeanonymizeRequest: {
            /** Text */
            text: string;
            replacement_map: components["schemas"]["ReplacementMap"];
        };
        /** DeanonymizeResponse */
        DeanonymizeResponse: {
            /** Original Text */
            original_text: string;
            /** Warnings */
            warnings?: string[];
        };
        /** DetectedEntity */
        DetectedEntity: {
            category: components["schemas"]["EntityCategory"];
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Text */
            text: string;
            /** Confidence */
            confidence: number;
            /**
             * Source
             * @default regex
             * @enum {string}
             */
            source: "regex" | "dictionary" | "ner" | "manual";
            /** Corroborated By */
            corroborated_by?: string[];
            validation: components["schemas"]["ValidationStatus"];
            /** Entity Group Id */
            entity_group_id?: string | null;
            /** Canonical Text */
            canonical_text?: string | null;
            /** @default accepted */
            status: components["schemas"]["EntityStatus"];
        };
        /** DocumentProcessResponse */
        DocumentProcessResponse: {
            document: components["schemas"]["ProcessedDocument"];
            /** Entities */
            entities: components["schemas"]["DetectedEntity"][];
            /** Anonymized Text */
            anonymized_text: string;
            replacement_map: components["schemas"]["ReplacementMap"];
            /** Offset Map */
            offset_map?: components["schemas"]["OffsetMapEntry"][];
        };
        /**
         * EntityCategory
         * @enum {string}
         */
        EntityCategory: "PESEL" | "NIP" | "REGON" | "ID_CARD" | "PASSPORT" | "KRS" | "BANK_ACCOUNT" | "PAYMENT_CARD" | "LAND_REGISTER" | "PHONE" | "EMAIL" | "URL" | "IP_ADDRESS" | "MAC_ADDRESS" | "API_KEY" | "VEHICLE" | "CASE_NUMBER" | "ADMIN_CASE" | "GPS" | "MONEY" | "PERSON" | "COMPANY" | "PUBLIC_INSTITUTION" | "ADDRESS" | "DATE" | "CUSTOM";
        /**
         * EntityStatus
         * @enum {string}
         */
        EntityStatus: "accepted" | "rejected";
        /** ExportRequest */
        ExportRequest: {
            /** Anonymized Text */
            anonymized_text: string;
            /**
             * Format
             * @enum {string}
             */
            format: "docx" | "pdf";
            /** Blocks */
            blocks?: components["schemas"]["Block"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Models Loaded */
            models_loaded: boolean;
        };
        /** InfoResponse */
        InfoResponse: {
            /** Version */
            version: string;
            /** Languages */
            languages: string[];
            /** Categories */
            categories: string[];
            /** Plan */
            plan: {
                [key: string]: unknown;
            };
            /** License Status */
            license_status: string;
            /**
             * Update Available
             * @default false
             */
            update_available: boolean;
            /** Latest Version */
            latest_version?: string | null;
            /** Degraded Reason */
            degraded_reason?: string | null;
        };
        /** OffsetMapEntry */
        OffsetMapEntry: {
            /** Original Start */
            original_start: number;
            /** Original End */
            original_end: number;
            /** Anonymized Start */
            anonymized_start: number;
            /** Anonymized End */
            anonymized_end: number;
            /** Token */
            token: string;
            /** Category */
            category: string;
        };
        /** ProcessedDocument */
        ProcessedDocument: {
            /** Filename */
            filename: string;
            /**
             * Format
             * @enum {string}
             */
            format: "txt" | "docx" | "pdf" | "png" | "jpg" | "heic";
            /**
             * Source
             * @enum {string}
             */
            source: "parsed" | "ocr";
            /** Page Count */
            page_count: number;
            /** Text */
            text: string;
        };
        /** PromptTemplateResponse */
        PromptTemplateResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Description */
            description: string;
            /** Body */
            body: string;
            /** Tags */
            tags: string[];
            /** Version */
            version: string;
        };
        /** ReplacementEntry */
        ReplacementEntry: {
            /** Token */
            token: string;
            /** Category */
            category: string;
            /** Canonical Text */
            canonical_text: string;
            /** Variants */
            variants?: string[];
        };
        /** ReplacementMap */
        ReplacementMap: {
            /** Entries */
            entries: components["schemas"]["ReplacementEntry"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Document Fingerprint */
            document_fingerprint: string;
        };
        /** UsageResponse */
        UsageResponse: {
            /** Period */
            period: string;
            /** Requests */
            requests: number;
            /** Documents */
            documents: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValidationStatus
         * @enum {string}
         */
        ValidationStatus: "passed" | "failed" | "not_applicable";
        /** ProblemResponse */
        ProblemResponse: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /**
             * Instance
             * @default null
             */
            instance: string | null;
            /**
             * Errors
             * @default null
             */
            errors: unknown | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    info_v1_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
        };
    };
    analyze_v1_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anonymize_endpoint_v1_anonymize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnonymizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnonymizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deanonymize_endpoint_v1_deanonymize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeanonymizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeanonymizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_endpoint_v1_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Anonymized document export. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                    "application/pdf": string;
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request payload exceeds the configured limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    process_document_v1_documents_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_process_document_v1_documents_process_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompts_v1_prompts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplateResponse"][];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request payload exceeds the configured limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    get_prompt_v1_prompts__prompt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplateResponse"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Missing or invalid API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Prompt template was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Request payload exceeds the configured limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Validation error. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    usage_v1_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
        };
    };
}
